### ISSUE TITLE
"viewer.get(...).addMarker is not a function" on diagramLoaded function

### ISSUE THREAD

**Issue by ElieLP** [bpmn-io/bpmn-js-diffing#1]
I'm trying to run an instance on a desktop. But when I try to open index.html on my web browser, I can see and compare two BPMN, But no diff changes are visible.
![image](https://user-images.githubusercontent.com/12176563/57623204-94478900-758f-11e9-910c-53f5b4cec2a6.png)

Thank you

**Comment by nikku** [comment]
Happy to take PRs that improve this.
